---
title: "Growshrink_Rnotebook"
output: html_notebook
---

This R notebook aims to explore the potential applications of [grow-shrink](https://doi.org/10.48550/arXiv.1407.8088)

This notebook utilizes the bnlearn library for its implementation of growshrink.

```{r}
library(Rgraphviz)
library(bnlearn)
```

Getting the data from csv files stored locally on device

```{r}
# Dubee
path_lsds_15 <- file.choose()
data_lsds_15 <- read.csv(path_lsds_15, header = FALSE)
```

```{r}
# Keune 2015
path_lsds_9 <- file.choose()
data_lsds_9 <- read.csv(path_lsds_9, header = FALSE)
```

```{r}
# Keune 2016
path_lsds_30 <- file.choose()
data_lsds30 <- read.csv(path_lsds_30, header = FALSE)
```

```{r}
# Ko 2020 1 of 2
path_lsds_41 <- file.choose()
data_lsds41 <- read.csv(path_lsds_41, header = FALSE)
```

```{r}
# Ko 2020 2 of 2
# micro ct
path_mct_lsds_40 <- file.choose()
# histomorphometry
path_hist_lsds_40 <- file.choose()
# bone
path_bone_lsds_40 <- file.choose()

data_mct_lsds_40 <- read.csv(path_mct_lsds_40, header = FALSE)
data_hist_lsds40 <- read.csv(path_hist_lsds_40, header = FALSE)
data_bone_lsds40 <- read.csv(path_bone_lsds_40, header = FALSE)
```

To start Convert it to a dataframe.

```{r}
data_lsds_15 <- as.data.frame(data_lsds_15)

data_lsds_15
```

Looks good! Let's run growshrink

```{r}
dag <- bnlearn::gs(data_lsds_15)

graph_dag <- bnlearn::as.graphNEL(dag)

plot(graph_dag)
```